import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import process from "node:process";
import { findRepoRoot, loadConfig } from "./audit/config/load.ts";
import { collectScanFiles } from "./audit/core/collect.ts";
import { CATALOG_REL_PATH, normalizeRelPath } from "./audit/core/shared.ts";
import { buildSkillIndex } from "./audit/core/skill-roots.ts";
import { collectSsotEntries, type SsotFileEntry } from "./audit/core/ssot-collect.ts";

export interface CatalogOptions {
	root?: string;
	check?: boolean;
}

export interface CatalogCheckResult {
	ok: boolean;
	missing: boolean;
	stale: boolean;
	expected: string;
	actual: string | null;
	entries: SsotFileEntry[];
}

function renderCatalog(entries: SsotFileEntry[]): string {
	const lines = [
		"# Skeleton catalog",
		"",
		"Generated by `skeleton catalog`. Gitignored — regenerate locally; do not commit.",
		"",
		"Agents: skim this list, then read only the SSOT line / first ~20 lines of a candidate before opening the full paper.",
		"",
		"| Summary | Path |",
		"| ------- | ---- |",
	];
	for (const e of entries) {
		const summary = e.summary.replace(/\|/g, "\\|");
		lines.push(`| ${summary} | [${e.path}](../${e.path}) |`);
	}
	lines.push("");
	return lines.join("\n");
}

export function buildCatalogContent(root: string): { content: string; entries: SsotFileEntry[] } {
	const config = loadConfig(root);
	const skillIndex = buildSkillIndex(root, config.skillOwnership);
	const files = collectScanFiles(config, root, skillIndex);
	const { entries } = collectSsotEntries(files, root);
	return { content: renderCatalog(entries), entries };
}

export function checkCatalog(root: string): CatalogCheckResult {
	const { content: expected, entries } = buildCatalogContent(root);
	const abs = join(root, CATALOG_REL_PATH);
	if (!existsSync(abs)) {
		return { ok: false, missing: true, stale: false, expected, actual: null, entries };
	}
	const actual = readFileSync(abs, "utf8");
	const stale = actual !== expected;
	return { ok: !stale, missing: false, stale, expected, actual, entries };
}

export function writeCatalog(root: string): { path: string; entries: SsotFileEntry[] } {
	const { content, entries } = buildCatalogContent(root);
	const abs = join(root, CATALOG_REL_PATH);
	mkdirSync(dirname(abs), { recursive: true });
	writeFileSync(abs, content, "utf8");
	return { path: normalizeRelPath(CATALOG_REL_PATH), entries };
}

/** Warn-only catalog drift for local audit; skip when CI=true. */
export function catalogAuditWarnings(root: string): string[] {
	if (process.env.CI === "true") return [];
	const result = checkCatalog(root);
	if (result.missing) {
		return [
			`${CATALOG_REL_PATH} missing — run \`skeleton catalog\` so agents can skim SSOT summaries`,
		];
	}
	if (result.stale) {
		return [`${CATALOG_REL_PATH} outdated — run \`skeleton catalog\` to refresh`];
	}
	return [];
}

export function runCatalogCli(options: CatalogOptions = {}): number {
	const root = options.root ?? findRepoRoot();
	if (options.check) {
		const result = checkCatalog(root);
		if (result.missing) {
			console.error(`catalog: missing ${CATALOG_REL_PATH} — run \`skeleton catalog\``);
			return 0; // warn-only exit
		}
		if (result.stale) {
			console.error(`catalog: ${CATALOG_REL_PATH} is outdated — run \`skeleton catalog\``);
			return 0;
		}
		console.log(`catalog: ${CATALOG_REL_PATH} up to date (${result.entries.length} entries)`);
		return 0;
	}
	const written = writeCatalog(root);
	console.log(`catalog: wrote ${written.path} (${written.entries.length} entries)`);
	return 0;
}
